# Go
# Build and test your Go application.
# Add steps that save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

pool:
  vmImage: 'vs2017-win2016'

variables:
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  GOPATH: '$(system.defaultWorkingDirectory)' # Go workspace path
  modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code

steps:
- powershell: |
    New-Item -Path $env:GOBIN -ItemType Directory -Force
    New-Item -Path $env:GOPATH/pkg -ItemType Directory -Force
    New-Item -Path $env:modulePath -ItemType Directory -Force
    robocopy $env:GOPATH $env:modulePath /e /move /xd $env:GOBIN $env:modulePath
    Write-Host "##vso[task.prependpath]$env:GOBIN"
    Write-Host "##vso[task.prependpath]$env:GOROOT)/bin"
  displayName: 'Set up the Go workspace'

- bash: |
    if [ -f Gopkg.toml ]; then
        curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
        dep ensure
    fi

- powershell: |
    go version
    go get -v -t -d ./...
    go get github.com/jstemmer/go-junit-report
    go get github.com/axw/gocov/gocov
    go get github.com/AlekSi/gocov-xml
    go get -u gopkg.in/matm/v1/gocov-html
  workingDirectory: '$(modulePath)'
  displayName: 'Get dependencies'
  
- script: |
    go test -v -coverprofile=coverage.txt -covermode count 2>&1 | go-junit-report > junit.xml
    gocov convert coverage.txt > coverage.json    
    gocov-xml < coverage.json > coverage.xml
    gocov-html < coverage.json > index.html
    mkdir reports
    copy junit.xml ./reports/junit.xml
    copy coverage.xml ./reports/coverage.xml
    copy index.html ./reports/index.html
  continueOnError: 'true'
  workingDirectory: '$(modulePath)'
  displayName: 'Run unit tests'
  
- script: |
    go build -v
  workingDirectory: '$(modulePath)'
  continueOnError: 'true'
  displayName: 'Build app'

- task: PublishTestResults@2
  inputs:
    testRunner: JUnit
    testResultsFiles: '$(modulePath)/reports/junit.xml'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: '$(modulePath)/reports/coverage.xml'
    reportDirectory: '$(modulePath)/reports/'

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'Test Reports'
    targetPath: '$(modulePath)/reports/'
