# Go
# Build and test your Go application.
# Add steps that save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger: none

pool:
  vmImage: 'vs2017-win2016'

variables:
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  GOPATH: '$(system.defaultWorkingDirectory)' # Go workspace path
  modulePath: 'src/github.com/$(build.repository.name)' # Path to the module's code

steps:
- checkout: self
  path: $(modulePath)

- powershell: |
    New-Item -Path $env:GOBIN -ItemType Directory -Force
    New-Item -Path $env:GOPATH/pkg -ItemType Directory -Force
    Write-Host "##vso[task.prependpath]$env:GOBIN"
    Write-Host "##vso[task.prependpath]$env:GOROOT/bin"
  displayName: "Setting up Go path variables"

- bash: |
    if [ -f Gopkg.toml ]; then
        curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
        dep ensure
    fi
  displayName: "Install dep"

- script: |
    go version
    go get -v -t -d ./...
    go get github.com/jstemmer/go-junit-report
    go get github.com/axw/gocov/gocov
    go get github.com/AlekSi/gocov-xml
    go get -u gopkg.in/matm/v1/gocov-html
  displayName: 'Get dependencies'
  
- script: |
    go test -v -coverprofile=coverage.txt -covermode count | go-junit-report > junit.xml
    gocov convert coverage.txt > coverage.json    
    type coverage.json | gocov-xml > coverage.xml
    type coverage.json | gocov-html > index.html
    mkdir reports
    move .\junit.xml .\reports\junit.xml
    move .\coverage.xml .\reports\coverage.xml
    move .\index.html .\reports\index.html
  displayName: 'Run unit tests'
  
- script: |
    go build -v -o $(GOBIN)\pipeline-go.exe
  displayName: 'Build app'

- task: PublishTestResults@2
  inputs:
    testRunner: JUnit
    testResultsFiles: '**/reports/junit.xml'
  condition: always()

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: '**/reports/coverage.xml'
    reportDirectory: '**/reports/'
  condition: always()

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'App'
    targetPath: $(GOBIN)
